Repository LGHV-team1/final-project, pull requests merged in 2023-11, with the labels that each got.

#10 feat: "Review 수정 기능 추가"
  .gitmessage
  contents/views.py
Labels: 개발, 수정

#19 Feat/front
  .github/ISSUE_TEMPLATE/github-issue-template.md
  .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
  .gitmessage
  README.md
  package-lock.json
  package.json
  public/kakao.png
  public/logo192.png
  public/logo512.png
  src/App.js
  src/components/Nav.scss
  src/components/NaverButton.js
  src/components/button.js
  src/components/googleButton.js
  src/components/header.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/header2.js
  src/components/kakaoButton.js
  src/components/login.js
  src/components/logo.png
  src/components/redirection.js
  src/components/register.js
  src/components/style.scss
  src/images/google_btn.png
  src/images/naver_btn.png
  src/images/pngwing.com.png
  src/page/Home.js
  src/page/Main.js
  src/page/Mypage.js
  src/page/login.js
  src/page/register.js
Labels: 수정

#24 [feat] : preprocessing and CF modeling
  .github/ISSUE_TEMPLATE/github-issue-template.md
  .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
  .gitmessage
  NCF.ipynb
  VOD전처리.ipynb
  협업필터링.ipynb
Labels: 제안, 수정

#27 feat : 크롤링, 폴더 생성
  모델/NCF.ipynb
  모델/협업필터링.ipynb
  전처리/VOD전처리.ipynb
  전처리/vod_data_addSummary.csv
  전처리/vod_list_preprocess.ipynb
Labels: 개발

#21 [Feat]: "VOD 상세 페이지 노출"
  contents/serializers.py
  requirements.txt
  wishlists/migrations/0002_alter_wishlist_user_alter_wishlist_vod.py
Labels: 개발

#34 [Feat]: "상세페이지 구현"
  src/App.css
  src/components/Button.js
  src/components/Rank.js
  src/components/Review.js
  src/page/Detail.js
  src/page/Login.js
Labels: 개발

#36 vod 데이터에 크롤링 변수 추가해봄. 몇몇 문제 발생
  전처리/vod8,9통합.ipynb
Labels: 분석

#39 [Back - Refactor] : "contents 띄어쓰기 무시한 검색 추가."
  .github/pull_request_template.md
  accounts/migrations/0001_initial.py
  contents/management/commands/dbimgget.py
  contents/management/commands/dbinsert.py
  contents/management/commands/dbinserttest.py
  contents/migrations/0001_initial.py
  contents/migrations/0002_remove_vod_runningtime.py
  contents/migrations/0003_alter_vod_description_alter_vod_imgpath.py
  contents/models.py
  contents/views.py
  reviews/migrations/0001_initial.py
  wishlists/migrations/0001_initial.py
  wishlists/migrations/0002_alter_wishlist_user_alter_wishlist_vod.py
Labels: 버그, 수정

#40 VOD 8,9월 전처리 코드 수정
  모델/NCF.ipynb
  전처리/VOD전처리.ipynb
  전처리/vod8,9통합.ipynb
Labels: 분석

#42 feat : 전처리 방법 통합
  전처리/vod, content 통합 전처리(크롤링).ipynb
  전처리/vod,content_score통합.ipynb
  전처리/vod_all.csv
Labels: 분석

#43 Back - [Fix] : "소셜로그인 오류 수정"
  .gitmessage
  accounts/admin.py
  accounts/migrations/0001_initial.py
  accounts/urls.py
  accounts/views.py
  config/settings.py
  config/urls.py
  contents/admin.py
  contents/migrations/0001_initial.py
  contents/migrations/0002_alter_vod_name_no_space.py
  reviews/migrations/0001_initial.py
  reviews/urls.py
  reviews/views.py
  wishlists/migrations/0001_initial.py
Labels: 버그

#44 feat : vod, content 모델 적용할 데이터셋 생성
  전처리/content89.csv
  전처리/content_score통합.ipynb
  전처리/vod,content_score통합.ipynb
  전처리/vod8,9통합.ipynb
  전처리/vod89.csv
Labels: 분석, 모델링

#51 docs : 아이템 기반 추천 구현 문서 추가
  전처리/vod_contents_based_recommendation.ipynb
Labels: 분석

#53 [Back-Feat] : "Image get 생성"
  accounts/migrations/0001_initial.py
  contents/management/commands/dbinsert.py
  contents/migrations/0001_initial.py
  contents/migrations/0002_alter_vod_name_no_space.py
  contents/models.py
  reviews/migrations/0001_initial.py
  wishlists/migrations/0001_initial.py
Labels: 개발

#52 [Front - Feat] : "마이페이지 위시리스트 나의리뷰 구현"
  package-lock.json
  package.json
  src/App.js
  src/Socialgoogle.js
  src/Socialkakao.js
  src/Socialnaver.js
  src/api/ApiService.js
  src/components/KakaoButton.js
  src/components/MiniSlide.js
  src/components/Modal/ModalProfile.js
  src/components/Modal/ModalProfile.module.css
  src/components/MyReview.js
  src/components/XKakaoLogin.js
  src/components/footer/Footer.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/images/profile_boy.png
  src/images/profile_girl.png
  src/images/profile_man.png
  src/images/profile_woman.png
  src/page/Login.js
  src/page/Mypage.js
Labels: 개발

#54 Feat/front
  src/App.css
  src/App.js
  src/components/Button.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Rank.js
  src/components/Review.js
  src/components/Star.js
  src/components/footer/Footer.css
  src/components/footer/Footer2.js
  src/components/header/Header.js
  src/page/Detail.js
  src/page/Home.js
  src/page/Register.js
Labels: 버그, 개발

#55 [feat] : 전처리 추가사항 수정
  전처리/content_score통합.ipynb
  전처리/vod, content 통합 전처리(크롤링).ipynb
  전처리/vod8,9통합.ipynb
Labels: 분석

#58 [docs] : 전저리(크롤링) 코드 수정
  전처리/vod, content 통합 전처리(크롤링).ipynb
Labels: 분석

#60 [Front - feat] 리덕스 툴깃 사용한 전역 상태 관리
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Input.js
  src/components/Rank.js
  src/components/Review.js
  src/components/Star.js
  src/components/XKakaoLogin.js
  src/components/Xheader.js
  src/components/Xlogin.js
  src/index.js
  src/page/Home.js
  src/page/Mypage.js
  src/page/Search.js
  src/redux/rankSlice.js
  src/redux/searchSlice.js
  src/redux/store/store.js
Labels: 개발

#62 [Back-Feat] : "actor image 가져오기, 회원정보 수정"
  accounts/migrations/0001_initial.py
  accounts/serializers.py
  config/settings.py
  contents/management/commands/dbinsert.py
  contents/migrations/0001_initial.py
  contents/models.py
  contents/serializers.py
  reviews/migrations/0001_initial.py
  wishlists/migrations/0001_initial.py
Labels: 버그, 개발, 수정

#59 [feat] : content score 생성을 위한 전처리 수행 & c_score 생성
  전처리/content_score재생성.ipynb
  전처리/content_series_nm전처리.ipynb
  전처리/vod_series_nm전처리.ipynb
Labels: 분석, 모델링

#64 [Front - feat]
  src/App.js
  src/components/Header.js
  src/components/Star.js
  src/page/Detail.js
  src/page/Search.js
Labels: 개발

#67 [Front - Feat] : "이메일 중복 처리, 회원가입 에러 알림"
  src/Socialgoogle.js
  src/Socialkakao.js
  src/Socialnaver.js
  src/api/ApiService.js
  src/components/Header.js
  src/components/Modal/ModalChangeinfo.js
  src/components/Modal/ModalChangeinfo.module.css
  src/components/Modal/ModalProfile.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/page/Login.js
  src/page/Mypage.js
  src/page/Register.js
  src/page/Search.js
Labels: 개발, 수정

#68 [Back - Fix] : "회원가입 및 로그인 버그 처리"
  accounts/admin.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_username.py
  accounts/migrations/0003_alter_user_username.py
  accounts/migrations/0004_remove_user_has_stb_user_stbnumber.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  config/settings.py
  contents/migrations/0001_initial.py
  manage.py
  reviews/migrations/0001_initial.py
  reviews/serializers.py
  reviews/urls.py
  reviews/views.py
  templates/account/email/email_confirmation_signup_message.html
  wishlists/migrations/0001_initial.py
Labels: 개발

#69 [Feat/Fix] : "contents/actor 이미지 수정, gitaction 을 이용한 배포"
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/githubaction.yaml
  config/settings.py
  config/urls.py
  config/views.py
  contents/management/commands/dbinsert.py
  contents/models.py
  docker-compose.yml
  dockerfile
  requirements.txt
  task-definition.json
Labels: 버그, 개발

#94 [Feat- front] 디테일 페이지 예고편 기능 추가
  package-lock.json
  package.json
  src/components/Modal.js
  src/components/Review.js
  src/components/Spinner.js
  src/components/Star.js
  src/images/no_img.jpg
  src/images/noimage.png
  src/images/noimagebg.png
  src/images/noimageps.png
  src/index.css
  src/page/Detail.js
  src/page/Login.js
  src/page/Search.js
Labels: 개발

#99 [Back-Feat,Fix] : "recommends App 추가, contents,accounts수정"
  accounts/migrations/0002_alter_user_stbnumber.py
  accounts/models.py
  config/settings.py
  config/urls.py
  contents/management/commands/dbinsert.py
  contents/models.py
  contents/serializers.py
  contents/urls.py
  contents/views.py
  recommends/__init__.py
  recommends/admin.py
  recommends/apps.py
  recommends/management/commands/recinsert.py
  recommends/migrations/0001_initial.py
  recommends/migrations/__init__.py
  recommends/models.py
  recommends/serializers.py
  recommends/tests.py
  recommends/urls.py
  recommends/views.py
Labels: 개발, 수정
