Repository LGHV-team1/final-project, pull requests merged in 2023-12, with the labels that each got.

#100 [Back-Feat] : " contents 세부 카테고리 진입"
  contents/management/commands/dbinsert.py
  contents/urls.py
  contents/views.py
  recommends/urls.py
  recommends/views.py
  reviews/serializers.py
  reviews/views.py
Labels: 버그, 개발

#102 [Back - Feat,Fix] : "초성 검색, 리뷰 수정삭제, conflict 수정"
  contents/management/commands/dbchoseong.py
  contents/migrations/0004_vod_choseong.py
  contents/models.py
  contents/urls.py
  contents/views.py
  reviews/serializers.py
  reviews/urls.py
  reviews/views.py
Labels: 버그, 개발

#103 [Back-Refactor] : "회원가입시 stbnum 기입 기능"
  .DS_Store
  accounts/adapters.py
  accounts/serializers.py
  config/settings.py
  pull_request_template.md
Labels: 수정

#104 [Back-fix] : "vodreveiw url 수정 "
  contents/urls.py
Labels: 버그

#105 [Back-fix] : "http 통신, 회원가입시 셋탑번호 미기입 처리"
  .github/workflows/githubaction.yaml
  accounts/adapters.py
  accounts/serializers.py
  config/settings.py
Labels: 버그

#108 [Back - Feat] : "접속 시 csrfToken get"
  config/views.py
  contents/views.py
Labels: 버그

#65 feat : vod 목록에 count(vod별 총 횟수) 추가, 전처리 코드 수정
  전처리/vod, content 통합 전처리(크롤링).ipynb
Labels: 분석

#111 [Back-Feat] : "배우 검색, 세션 저장"
  config/settings.py
  contents/management/commands/dbinsert.py
  contents/migrations/0005_vod_actorsimage_alter_vod_actors.py
  contents/models.py
  contents/views.py
Labels: 개발, 수정

#113 [Feat - front] 영화 kids tv 전체 페이지 구성
  package-lock.json
  package.json
  src/App.js
  src/components/Dropdown.js
  src/components/Header.js
  src/components/MiniSlide.js
  src/components/ViewReview.js
  src/hook/useCategory.js
  src/images/rank/1.png
  src/images/rank/2.png
  src/page/Detail.js
  src/page/Kids.js
  src/page/Login.js
  src/page/Movie.js
  src/page/Register.js
  src/page/Search.js
  src/page/Tv.js
  src/redux/categorySlice.js
  src/redux/store/store.js
  tailwind.config.js
Labels: 개발

#118 [Feat- front] tv movie kids 장르 별 페이지 구성
  src/api/ApiService.js
  src/components/Dropdown.js
  src/components/MiniSlide.js
  src/components/ShowData.js
  src/jsconfig.js
  src/page/Detail.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Search.js
  src/page/Tv.js
Labels: 개발

#124 docs : vod 전처리 최신화
  모델/vod_modeling.ipynb
  전처리/vod8,9통합.ipynb
Labels: 분석, 모델링

#126 [Back-Refactor] : "db변경 및 vod_id 삽입"
  accounts/migrations/0001_initial.py
  config/settings.py
  contents/management/commands/dbinsert.py
  contents/migrations/0001_initial.py
  contents/models.py
  recommends/management/commands/recinsert.py
  recommends/migrations/0001_initial.py
  reviews/migrations/0001_initial.py
  wishlists/migrations/0001_initial.py
Labels: 수정

#125 [Feat - front] tv movie kids 정렬 버튼 추가
  src/components/Dropdown.js
  src/components/ShowData.js
  src/components/SortData.js
  src/components/ViewReview.js
  src/page/Kids.js
  src/page/Login.js
  src/page/Movie.js
  src/page/Tv.js
Labels: 개발

#128 [Front-Docs] : "S3 CI/CD를 위한 gitaction 추가"
  .github/workflows/frontgitaction.yaml
Labels: 개발

#132 [Front - Feat] : "axios header에 Token 추가"
  src/api/ApiService.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Modal/ModalChangeinfo.js
  src/components/Modal/ModalProfile.js
  src/components/MyReview.js
  src/components/MyWish.js
  src/images/dark.png
  src/page/Detail.js
  src/page/Kids.js
  src/page/Login.js
  src/page/Mypage.js
  src/page/Register.js
  src/page/Search.js
  src/page/Tv.js
Labels: 개발

#133 [Back-Refactor] : "wishlist serializers 수정, jwt 토큰 사용"
  config/settings.py
  contents/urls.py
  contents/views.py
  recommends/views.py
  wishlists/serializers.py
Labels: 개발

#135 [Refactor] : "allowed host 추가"
  config/settings.py
Labels: 개발, 수정

#140 [docs] : 모델링 추천 결과
  모델/c_score_modeling.ipynb
  모델/vod_modeling.ipynb
  전처리/10월_전처리.ipynb
Labels: 분석, 모델링

#146 [Feat - front] 메인페이지 추천 데이터 추가
  src/components/MiniSlide.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/SortData.js
  src/components/Star.js
  src/page/Detail.js
  src/page/Home.js
  src/page/Login.js
  src/page/Main.js
  src/page/Mypage.js
  src/page/Register.js
  src/page/Search.js
  src/page/Tv.js
  tailwind.config.js
Labels: 개발

#141 feat : c_score 이용한 장르 기반 추천
  모델/genre_based_recommendation_c_score.ipynb
  모델/vod_SVD.ipynb
  전처리/content_score재생성.ipynb
  전처리/vod, content 통합 전처리(크롤링).ipynb
  전처리/vod_list_preprocess.ipynb
Labels: 🍎모델링

#148 [feat] : score 최종 생성 및 비율 변경
  score/5score.ipynb
  score/click & click_plus생성.ipynb
  score/content_paper_score.ipynb
  score/vod_paper_score.ipynb
  전처리/content_series_nm전처리_origin.ipynb
Labels: 👊분석, 🍎모델링, Priority: Medium

#160 [docs] : 데이터 수정, 모델링 추가
  모델/vod_modeling.ipynb
  전처리/10월_전처리.ipynb
  전처리/vod8,9통합.ipynb
Labels: 👊분석, 🍎모델링

#162 [Front -Feat] : "Proxy 설정 추가"
  package.json
  src/api/ApiService.js
  src/components/Helload.js
  src/components/MyReview.js
  src/components/MyWish.js
  src/page/Detail.js
  src/page/Home.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 😂버그, Priority: High

#167 [Deploy - Fix] : "csrftoken 헤더 및 소셜로그인 URL 수정"
  package.json
  src/api/ApiService.js
  src/components/Helload.js
  src/components/MyReview.js
  src/components/MyWish.js
  src/page/Detail.js
  src/page/Home.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 💻Front, 〄CI/CD

#166 [Back - Feat] : "dj-rest-auth login 커스텀"
  .gitignore
  accounts/serializers.py
  config/settings.py
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Low

#171 [Back- Fix] : "로그인 안되는 버그 수정"
  accounts/serializers.py
Labels: 🥺Back, 💡수정, Priority: Urgent

#174 [Front - Feat] : "Private Router 구현"
  package-lock.json
  package.json
  src/App.js
  src/LoginRouter.js
  src/PrivateRouter.js
  src/components/MiniSlide.js
Labels: 👨🏻‍💻개발, 💻Front

#177 [docs] : surprise knnbaseline 모델
  모델/vod_modeling.ipynb
  모델/vod_surprise.ipynb
Labels: 👊분석, 🍎모델링

#179 feat : 시간대별 추천 모델
  모델/c_score_modeling.ipynb
  모델/time_based_recommendation.ipynb
Labels: 👊분석, 🍎모델링

#181 [feat] : NCT 모델 생성
  모델/NCF_cd28_score.ipynb
Labels: 👊분석, 🍎모델링

#176 [Back-Feat] : "리뷰 포스터를 위한 시리얼라이저 수정"
  reviews/serializers.py
Labels: 💻Front, Priority: Low

#178 [Feat] : "Mongodb CQRS 적용 1차"
  accounts/apps.py
  config/settings.py
  contents/apps.py
  contents/management/commands/dbinsert.py
  contents/urls.py
  contents/views.py
  recommends/apps.py
  reviews/apps.py
  wishlists/apps.py
Labels: Priority: Low

#180 [Feat] : "나의리뷰 포스터 렌더링"
  src/components/MyReview.js
Labels: 💻Front, Priority: Low

#183 [Deploy] : "private router, 리뷰 포스터 렌더링"
  package-lock.json
  package.json
  src/App.js
  src/LoginRouter.js
  src/PrivateRouter.js
  src/components/MiniSlide.js
  src/components/MyReview.js
Labels: 💻Front, 〄CI/CD

#184 [Deploy] : "리뷰 포스터를 위한 시리얼라이저 수정"
  reviews/serializers.py
Labels: 〄CI/CD

#185 [Back - Feat] : "검색 제목 인물 초성 나눠서 구현"
  contents/urls.py
  contents/views.py
Labels: 👨🏻‍💻개발, 🥺Back

#186 [Deploy] : "검색 제목 인물 초성 나눠서 구현"
  contents/urls.py
  contents/views.py
Labels: 🥺Back, 〄CI/CD

#188 [Back - Fix] : "소셜로그인 오류 수정"
  accounts/views.py
Labels: 😂버그, 🥺Back, Priority: High

#189 [Deploy - Fix] : "소셜로그인 오류 수정"
  accounts/views.py
Labels: 😂버그, 🥺Back, 〄CI/CD

#190 [Back- Feat] : "Mongodb 도입을 통한 CQRS 적용"
  accounts/apps.py
  config/settings.py
  contents/apps.py
  contents/management/commands/dbinsert.py
  contents/urls.py
  contents/views.py
  recommends/apps.py
  recommends/views.py
  reviews/apps.py
  reviews/views.py
  wishlists/apps.py
  wishlists/urls.py
  wishlists/views.py
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Medium

#191 [Deploy- Feat] : "Mongodb 도입을 통한 CQRS 적용"
  accounts/apps.py
  config/settings.py
  contents/apps.py
  contents/management/commands/dbinsert.py
  contents/urls.py
  contents/views.py
  recommends/apps.py
  recommends/views.py
  reviews/apps.py
  reviews/views.py
  wishlists/apps.py
  wishlists/urls.py
  wishlists/views.py
Labels: 🥺Back, 〄CI/CD, Priority: High

#192 [Front - feat] 메인, 서브 레이아웃 구성
  src/App.js
  src/PrivateRouter.js
  src/components/DarkButton.js
  src/components/Dropdown.js
  src/components/Footer.js
  src/components/MiniSlide.js
  src/components/Modal.js
  src/components/MyReview.js
  src/components/RecMiniSlide.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ViewReview.js
  src/images/tmplogo.png
  src/index.css
  src/jsconfig.js
  src/layout/BeforeHeader.js
  src/layout/Footer.js
  src/layout/Header.js
  src/layout/MainLayout.js
  src/layout/SubLayout.js
  src/page/About.js
  src/page/Detail.js
  src/page/First.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Login.js
  src/page/Movie.js
  src/page/Mypage.js
  src/page/Register.js
  src/page/Search.js
  src/page/Tv.js
  tailwind.config.js
Labels: 👨🏻‍💻개발, 💻Front, Priority: Medium

#194 [Deploy - Front] : "다크모드, 소셜로그인, 검색창 나누기"
  src/App.js
  src/PrivateRouter.js
  src/api/ApiService.js
  src/components/DarkButton.js
  src/components/Dropdown.js
  src/components/Footer.js
  src/components/MiniSlide.js
  src/components/Modal.js
  src/components/MyReview.js
  src/components/RecMiniSlide.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ViewReview.js
  src/images/tmplogo.png
  src/index.css
  src/jsconfig.js
  src/layout/BeforeHeader.js
  src/layout/Footer.js
  src/layout/Header.js
  src/layout/MainLayout.js
  src/layout/SubLayout.js
  src/page/About.js
  src/page/Detail.js
  src/page/First.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Login.js
  src/page/Movie.js
  src/page/Mypage.js
  src/page/Register.js
  src/page/Search.js
  src/page/Tv.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
  tailwind.config.js
Labels: 💻Front, 〄CI/CD

#193 [modeling - docs] : Knnbaseline, SVD 모델 추가
  모델/lightfm.ipynb
  모델/vod_89train_10test.ipynb
  모델/vod_deepMF.ipynb
Labels: 👊분석, 🍎모델링

#197 docs : 시간대별 시청률 분석
  모델/time_based_recommendation.ipynb
Labels: 👊분석, 🍎모델링

#198 [Feat - front] : 반응형 UI 추가, 더보기 버그 수정
  package-lock.json
  package.json
  src/components/MiniSlide.js
  src/components/MyReview.js
  src/components/MyWish.js
  src/components/RecMiniSlide.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/SortData.js
  src/components/Top5.js
  src/layout/Footer.js
  src/layout/Header.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Mypage.js
  src/page/Search.js
  src/page/Tv.js
  tailwind.config.js
Labels: 😂버그, 👨🏻‍💻개발, 💻Front, Priority: High

#199 [Deploy - front] : 반응형 UI 추가, 더보기 버그 수정
  package-lock.json
  package.json
  src/components/MiniSlide.js
  src/components/MyReview.js
  src/components/MyWish.js
  src/components/RecMiniSlide.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/SortData.js
  src/components/Top5.js
  src/layout/Footer.js
  src/layout/Header.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Mypage.js
  src/page/Search.js
  src/page/Tv.js
  tailwind.config.js
Labels: 💻Front, 〄CI/CD

#200 [Front - Fix] : "소셜로그인 버그 수정"
  src/App.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 😂버그, 💻Front

#201 [Deploy- Fix] : "소셜로그인 버그 수정"
  src/App.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 😂버그, 〄CI/CD

#202 [front- Fix] : "소셜로그인 수정"
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 😂버그, 💻Front

#203 [Deploy- Fix] : "소셜로그인 수정"
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 💻Front, 〄CI/CD

#212 [Back- Feat] : "mongodb 중복 데이터 처리"
  accounts/apps.py
  contents/apps.py
  recommends/apps.py
  reviews/apps.py
  wishlists/apps.py
Labels: 👨🏻‍💻개발, 🥺Back, 〄CI/CD, Priority: High

#216 [modeling - docs] : knnbaseline, svd, baselineonly 모델 추가
  모델/vod_89train_10test.ipynb
Labels: 👊분석, 🍎모델링

#218 [feat] : content 8,9월 데이터로 surprise 모델 구현
  모델/content_surprise_click.ipynb
Labels: 🍎모델링

#223 docs : knnbaseline, svd, baselineonly 모델 추가
  모델/vod_89train_10test.ipynb
Labels: 👊분석, 🍎모델링

#225 [BACK- Fix] : "MONGODB 동기화 1회만 수행하도록 수정"
  Dockerfile
  accounts/apps.py
  contents/apps.py
  recommends/apps.py
  reviews/apps.py
  sync.py
  wishlists/apps.py
Labels: 👨🏻‍💻개발, 🥺Back, 〄CI/CD, Priority: High

#224 docs : 시간대별 추천 결과 추출 완료
  모델/time_based_recommendation.ipynb
  모델/time_based_result.ipynb
Labels: 👊분석, 🍎모델링

#227 [Fix - Front] : 검색 오류 수정
  public/index.html
  src/App.js
  src/LoginRouter.js
  src/PrivateRouter.js
  src/components/Button.js
  src/components/Dropdown.js
  src/components/Helload.js
  src/components/MiniSlide.js
  src/components/Modal.js
  src/components/Modal/ModalChangeinfo.js
  src/components/Modal/ModalProfile.js
  src/components/MyReview.js
  src/components/MyWish.js
  src/components/Rank.js
  src/components/RecMiniSlide.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/SortData.js
  src/components/Star.js
  src/components/Top5.js
  src/components/ViewReview.js
  src/hook/useCategory.js
  src/layout/BeforeHeader.js
  src/layout/Header.js
  src/layout/SubLayout.js
  src/page/About.js
  src/page/Detail.js
  src/page/First.js
  src/page/Kids.js
  src/page/Login.js
  src/page/Movie.js
  src/page/Mypage.js
  src/page/Register.js
  src/page/Search.js
  src/page/Tv.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 😂버그, 💻Front, Priority: High

#228 [Deploy - Front] : 검색 오류 수정
  public/index.html
  src/App.js
  src/LoginRouter.js
  src/PrivateRouter.js
  src/components/Button.js
  src/components/Dropdown.js
  src/components/Helload.js
  src/components/MiniSlide.js
  src/components/Modal.js
  src/components/Modal/ModalChangeinfo.js
  src/components/Modal/ModalProfile.js
  src/components/MyReview.js
  src/components/MyWish.js
  src/components/Rank.js
  src/components/RecMiniSlide.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/SortData.js
  src/components/Star.js
  src/components/Top5.js
  src/components/ViewReview.js
  src/hook/useCategory.js
  src/layout/BeforeHeader.js
  src/layout/Header.js
  src/layout/SubLayout.js
  src/page/About.js
  src/page/Detail.js
  src/page/First.js
  src/page/Kids.js
  src/page/Login.js
  src/page/Movie.js
  src/page/Mypage.js
  src/page/Register.js
  src/page/Search.js
  src/page/Tv.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 😂버그, 💻Front, 〄CI/CD

#232 [Back - Feat] : "새로운 유저에 대해 컨텐츠 받기, wishlist 로직 변경"
  accounts/apps.py
  accounts/migrations/0002_user_is_social_user_prefer_contents.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  contents/urls.py
  contents/views.py
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Medium

#233 [Deploy - Feat] : "새로운 유저에 대해 컨텐츠 받기, wishlist 로직 변경"
  accounts/apps.py
  accounts/migrations/0002_user_is_social_user_prefer_contents.py
  accounts/models.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  contents/urls.py
  contents/views.py
Labels: 🥺Back, 〄CI/CD

#238 [Front - Fix] : 검색, 위시 오류 수정
  src/App.js
  src/api/ApiService.js
  src/components/MiniSlide.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/Top5.js
  src/hook/useDebounce.js
  src/layout/Header.js
  src/page/Detail.js
  src/page/First.js
  src/page/Home.js
  src/page/Search.js
  src/page/__Search.js
Labels: 😂버그, 💻Front, Priority: High

#235 [Back- Feat] : "카테고리창에 띄울 각 카테코리별 가장 인기있는 영화"
  contents/urls.py
  contents/views.py
  recommends/admin.py
  recommends/management/commands/timeinsert.py
  recommends/migrations/0002_timerecommend.py
  recommends/models.py
  recommends/views.py
  sync.py
Labels: 🥺Back, Priority: High

#239 [Deploy-back] : "카테고리창에 띄울 각 카테코리별 가장 인기있는 영화"
  contents/urls.py
  contents/views.py
  recommends/admin.py
  recommends/management/commands/timeinsert.py
  recommends/migrations/0002_timerecommend.py
  recommends/models.py
  recommends/views.py
  sync.py
Labels: 🥺Back, 〄CI/CD

#237 docs : 알고리즘 별 성능비교 + 앙상블 모델 성능 비교
  모델/vod_89train_10test.ipynb
Labels: 👊분석, 🍎모델링

#240 [Front-Feat] : "신규유저 콘텐츠 선택 구현"
  package-lock.json
  package.json
  src/App.js
  src/api/ApiService.js
  src/components/Modal/ModalChangeinfo.js
  src/components/Modal/ModalChangeinfo.module.css
  src/components/Modal/ModalProfile.module.css
  src/components/MyReview.js
  src/page/Login.js
  src/page/SelectCategory.js
  src/page/SelectContents.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 👨🏻‍💻개발, 💻Front, Priority: Low

#241 [Deploy - Front] : "신규유저 콘텐츠 선택 구현"
  package-lock.json
  package.json
  src/App.js
  src/api/ApiService.js
  src/components/MiniSlide.js
  src/components/Modal/ModalChangeinfo.js
  src/components/Modal/ModalChangeinfo.module.css
  src/components/Modal/ModalProfile.module.css
  src/components/MyReview.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/Top5.js
  src/hook/useDebounce.js
  src/layout/Header.js
  src/page/Detail.js
  src/page/First.js
  src/page/Home.js
  src/page/Login.js
  src/page/Search.js
  src/page/SelectCategory.js
  src/page/SelectContents.js
  src/page/__Search.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 💻Front, 〄CI/CD

#248 [Back - Feat] : "시간대별 추천 API 생성"
  recommends/views.py
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Medium

#249 [Deploy - Feat] : "시간대별 추천 API 생성"
  recommends/views.py
Labels: 🥺Back, 〄CI/CD

#250 [Docs] : "requirements.txt pytimekr 추가"
  requirements.txt
  sync.py
Labels: 🥺Back, Priority: Low

#251 [Deploy] : "requirements.txt pytimekr 추가"
  requirements.txt
  sync.py
Labels: 🥺Back, 〄CI/CD

#252 [Fix] : "토요일이 평일로 인식되는 버그 해결"
  contents/management/commands/dbchoseong.py
  contents/management/commands/dbinsert.py
  recommends/views.py
Labels: 😂버그, Priority: High

#254 [Fix] : "tv pick url에 bigcategory로 serialize"
  contents/views.py
Labels: Priority: High

#255 [Deploy] : "tv pick url에 bigcategory로 serialize"
  contents/views.py
Labels: 🥺Back, 〄CI/CD

#256 [Refactor] : "관련 vod 추천 20개중 5개 제공"
  contents/views.py
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Low

#259 [Feat] : "카테고리버튼, 디테일 관련vod 구현"
  src/api/ApiService.js
  src/components/CategoryBtn.js
  src/components/MyWish.js
  src/components/Related.js
  src/page/Detail.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Tv.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 👨🏻‍💻개발, 💻Front

#260 [Deploy] :" 카테고리버튼, 디테일 관련vod 구현"
  src/api/ApiService.js
  src/components/CategoryBtn.js
  src/components/MyWish.js
  src/components/Related.js
  src/page/Detail.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Tv.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 💻Front, 〄CI/CD

#261 [Feat] : "신규 유저에 대한 2번 추천 API 작성"
  contents/views.py
  recommends/urls.py
  recommends/views.py
  requirements.txt
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Medium

#262 [Deploy] : "신규 유저에 대한 2번 추천 API 작성"
  contents/views.py
  recommends/urls.py
  recommends/views.py
  requirements.txt
Labels: 🥺Back, 〄CI/CD

#242 [feat] : content 데이터로 모델 생성
  score/c_score_category.ipynb
  score/content_score재생성.ipynb
  모델/content_surprise_click.ipynb
  모델/content_surprise_paper.ipynb
  모델/content_surprise_time.ipynb
Labels: 🍎모델링

#264 [Fix - Front]: 카테고리 페이지 버그 수정
  src/components/CategoryBtn.js
  src/components/MyWish.js
  src/components/Rank.js
  src/components/Related.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Tv.js
Labels: 😂버그, 💻Front, Priority: High

#265 [Deploy - Front]: 카테고리 페이지 버그 수정
  src/components/CategoryBtn.js
  src/components/MyWish.js
  src/components/Rank.js
  src/components/Related.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Tv.js
Labels: 😂버그, 💻Front, 〄CI/CD

#269 [Fix - Front] : 스크롤 버그 수정
  src/App.js
  src/components/CategoryBtn.js
  src/components/Review.js
  src/components/ScrollonTop.js
  src/index.js
  src/layout/Header.js
  src/page/Detail.js
Labels: 😂버그, 💻Front, Priority: High

#270 [Deploy -front] : "스크롤 버그 수정“
  src/App.js
  src/components/CategoryBtn.js
  src/components/Review.js
  src/components/ScrollonTop.js
  src/index.js
  src/layout/Header.js
  src/page/Detail.js
Labels: 😂버그, 💻Front, 〄CI/CD

#271 [Front - Fix] : "브라우저 창 크기에따른 이미지 비율 조정"
  src/components/CategoryBtn.js
  src/components/Rank.js
  src/components/Related.js
Labels: 😂버그, 💻Front

#280 [Back-Fix] : "review 가져올 때 user object MySQL에서 가져오도록 수정"
  contents/views.py
  recommends/views.py
Labels: 🥺Back, 💡수정, Priority: Urgent

#281 [Deploy - Hotfix] : "review 가져오기 수정"
  contents/views.py
  recommends/views.py
Labels: Priority: Urgent

#282 [Feat] : "시즌별 추천 API"
  config/settings.py
  recommends/urls.py
  recommends/views.py
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Low

#268 docs : 문서 추가
  모델/new_genre_based.py
  모델/time_based_result.ipynb
  모델/vod_89train_10test.ipynb
Labels: 🍎모델링

#283 [Back-Feat] : "신규 유저에 대한 사용자 기반 추천, wishlist 기반 추천"
  recommends/management/commands/scoreinsert.py
  recommends/migrations/0003_vod_score.py
  recommends/models.py
  recommends/urls.py
  recommends/views.py
  requirements.txt
Labels: 👨🏻‍💻개발, 🥺Back, Priority: Medium

#289 [Back - Fix] : "DB 리셋, User object는 MySQL에서 가져오도록 변경"
  .DS_Store
  contents/management/commands/dbinsert.py
  contents/migrations/0001_initial.py
  contents/views.py
  recommends/management/commands/recinsert.py
  recommends/migrations/0001_initial.py
  recommends/migrations/0002_timerecommend.py
  recommends/migrations/0003_vod_score.py
  reviews/migrations/0001_initial.py
  reviews/views.py
  sync.py
  wishlists/migrations/0001_initial.py
Labels: 🥺Back, 💡수정, Priority: Urgent

#290 [Deploy - Fix] : "DB 리셋, User object는 MySQL에서 가져오도록 변경"
  .DS_Store
  contents/management/commands/dbinsert.py
  contents/migrations/0001_initial.py
  contents/views.py
  recommends/management/commands/recinsert.py
  recommends/migrations/0001_initial.py
  recommends/migrations/0002_timerecommend.py
  recommends/migrations/0003_vod_score.py
  reviews/migrations/0001_initial.py
  reviews/views.py
  sync.py
  wishlists/migrations/0001_initial.py
Labels: 🥺Back, 〄CI/CD

#284 docs : 문서 추가
  모델/new_user_recommendation.py
  모델/practice.ipynb
  모델/vod_89train_10test.ipynb
  전처리/vod8,9통합.ipynb
Labels: 👊분석, 🍎모델링

#292 [Back-Fix] : "Kids 컨텐츠 부족으로 인한 에러 처리"
  contents/views.py
  sync.py
Labels: 😂버그, 🥺Back, Priority: Urgent

#293 [Feat - front]: 메인페이지 UI 변경
  package-lock.json
  package.json
  src/components/ArrowBtn.js
  src/components/CategoryBtn.js
  src/components/Dropdown.js
  src/components/MiniSlide.js
  src/components/RecMiniSlide.js
  src/components/Related.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/Streaming.js
  src/components/Top5.js
  src/images/MainTop/top1연인.jpg
  src/images/MainTop/top2범죄도시.jpg
  src/images/MainTop/top3런닝맨.jpg
  src/images/MainTop/top4꼬꼬무.jpg
  src/images/MainTop/top5최강배달꾼.jpg
  src/images/MainTop/가오갤.jpg
  src/images/MainTop/가오갤제목.png
  src/images/MainTop/가오갤제목2.webp
  src/images/MainTop/가오갤제목4.png
  src/images/MainTop/밀수.jpg
  src/images/MainTop/밀수제목.png
  src/images/MainTop/소방서.jpg
  src/images/MainTop/소방서제목.png
  src/images/MainTop/아바타.jpg
  src/images/MainTop/아바타제목.png
  src/images/MainTop/엘리멘탈.jpg
  src/images/MainTop/엘리멘탈제목.png
  src/images/seasonlogo.png
  src/index.js
  src/layout/BeforeHeader.js
  src/layout/Header.js
  src/layout/MainLayout.js
  src/page/Detail.js
  src/page/Home.js
  src/page/Search.js
Labels: 👨🏻‍💻개발, 💻Front, Priority: High

#294 [Deploy - front]: "메인페이지 UI 변경"
  package-lock.json
  package.json
  src/components/ArrowBtn.js
  src/components/CategoryBtn.js
  src/components/Dropdown.js
  src/components/MiniSlide.js
  src/components/Rank.js
  src/components/RecMiniSlide.js
  src/components/Related.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/Streaming.js
  src/components/Top5.js
  src/images/MainTop/top1연인.jpg
  src/images/MainTop/top2범죄도시.jpg
  src/images/MainTop/top3런닝맨.jpg
  src/images/MainTop/top4꼬꼬무.jpg
  src/images/MainTop/top5최강배달꾼.jpg
  src/images/MainTop/가오갤.jpg
  src/images/MainTop/가오갤제목.png
  src/images/MainTop/가오갤제목2.webp
  src/images/MainTop/가오갤제목4.png
  src/images/MainTop/밀수.jpg
  src/images/MainTop/밀수제목.png
  src/images/MainTop/소방서.jpg
  src/images/MainTop/소방서제목.png
  src/images/MainTop/아바타.jpg
  src/images/MainTop/아바타제목.png
  src/images/MainTop/엘리멘탈.jpg
  src/images/MainTop/엘리멘탈제목.png
  src/images/seasonlogo.png
  src/index.js
  src/layout/BeforeHeader.js
  src/layout/Header.js
  src/layout/MainLayout.js
  src/page/Detail.js
  src/page/Home.js
  src/page/Search.js
Labels: 💻Front, 〄CI/CD

#299 [Front - Feat] : "관심가진 컨텐츠 관련 제목 수정"
  src/components/ShowRec.js
  src/page/Home.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 💻Front, Priority: High

#300 [Deploy - Feat] : "관심가진 컨텐츠 관련 제목 수정"
  src/components/ShowRec.js
  src/page/Home.js
  src/page/tmp/Socialgoogle.js
  src/page/tmp/Socialkakao.js
  src/page/tmp/Socialnaver.js
Labels: 💻Front, 〄CI/CD

#301 refactor : db용 vod list 만드는 함수, 상세페이지 관련 컨텐츠 함수
  모델/detail_page_contents.py
  전처리/crawling.ipynb
  전처리/make_vod_list.py
  전처리/preprocess_for_crawling.py
  전처리/vod, content 통합 전처리(크롤링).ipynb
  전처리/vod_list_preprocess.ipynb
Labels: 🍎모델링

#302 [Feat - front]: 숏필름 페이지 구성
  src/App.js
  src/components/ArrowBtn.js
  src/components/CategoryBtn.js
  src/components/Helload.js
  src/components/Related.js
  src/components/Streaming.js
  src/components/Top5.js
  src/layout/Header.js
  src/page/Detail.js
  src/page/Home.js
  src/page/ShortFilm.js
Labels: 👨🏻‍💻개발, 💻Front, Priority: High

#305 [Back-Feat] : "기존 유저에 대한 가장 비슷한 사용자중 추천"
  recommends/management/commands/scoreinsert.py
  recommends/urls.py
  recommends/views.py
Labels: Priority: Low

#307 [Front] 추천 URL 변경
  src/page/Home.js
  src/page/ShortFilm.js
Labels: 💻Front, 💡수정, Priority: Urgent

#303 [Model] : 11월 추천 리스트 생성, heavy medium light 유저별 추천 성능 확인, 함수화
  모델/new_user_recommendation.py
  모델/practice.ipynb
  모델/recommend1.ipynb
  모델/vod_89train_10test.ipynb
  모델/vod_preprocessing.py
  전처리/10월_전처리.ipynb
Labels: 💡수정, 👊분석, 🍎모델링

#308 [Deploy] : "숏필름 추가, 추천 URL 변경"
  src/App.js
  src/components/ArrowBtn.js
  src/components/CategoryBtn.js
  src/components/Helload.js
  src/components/Related.js
  src/components/Streaming.js
  src/components/Top5.js
  src/layout/Header.js
  src/page/Detail.js
  src/page/Home.js
  src/page/ShortFilm.js
Labels: 💻Front, 〄CI/CD

#309 [Fix] : "인기 TOP 10 수정"
  recommends/views.py
Labels: 🥺Back, Priority: Urgent

#311 [Refactor] : "print문 제거, admin에서 장르기반도 보여주기."
  directory-visualizer-data.txt
  recommends/admin.py
  recommends/views.py
Labels: 🥺Back, Priority: Low

#314 [Feat] : "디테일페이지 내에서 인물검색 연결"
  src/layout/Header.js
  src/page/Detail.js
  src/page/Search.js
Labels: 👨🏻‍💻개발, 💻Front

#315 [Front]: snow 애니메이션 추가
  src/components/CategoryBtn.js
  src/components/MiniSlide.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/Snow.js
  src/index.css
  src/layout/Header.js
  src/page/First.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/ShortFilm.js
  src/page/Tv.js
Labels: 👨🏻‍💻개발, 💻Front, Priority: Medium

#316 [Deploy]: "인물검색, snow 애니메이션 추가"
  src/components/CategoryBtn.js
  src/components/MiniSlide.js
  src/components/Review.js
  src/components/ShowData.js
  src/components/ShowRec.js
  src/components/Snow.js
  src/index.css
  src/layout/Header.js
  src/page/Detail.js
  src/page/First.js
  src/page/Home.js
  src/page/Kids.js
  src/page/Movie.js
  src/page/Search.js
  src/page/ShortFilm.js
  src/page/Tv.js
Labels: 💻Front, 〄CI/CD

#317 [Feat] : "배우 검색시 띄어쓰기 제거 하지 않고 검색도 추가"
  contents/views.py
Labels: 🥺Back, Priority: Low

#320 [Back- Fix] : "위시리스트 기반 추천 vod_score heavy_score만 사용"
  recommends/views.py
Labels: 🥺Back, Priority: Urgent

#318 [Model] : score 최종 완성 및 score 별 성능 평가, 랜덤 추천 함수화
  score/5score.ipynb
  score/c_score_category.ipynb
  score/click & click_plus생성.ipynb
  score/content_paper_score.ipynb
  score/content_score통합.ipynb
  모델/content_surprise_click.ipynb
  모델/random_rec.py
Labels: 💡수정, 🍎모델링

#322 [Feat - front]: 숏필름 클릭 재생 조절
  src/components/MiniSlide.js
  src/components/Modal.js
  src/components/RecMiniSlide.js
  src/components/ShowData.js
  src/components/Snow.js
  src/components/Streaming.js
  src/components/Top5.js
  src/index.js
  src/layout/Header.js
  src/page/About.js
  src/page/Home.js
  src/page/Search.js
  src/page/ShortFilm.css
  src/page/ShortFilm.js
Labels: 👨🏻‍💻개발, 💻Front, Priority: High

#323 [Deploy - front]: "숏필름 클릭 재생 조절"
  src/components/MiniSlide.js
  src/components/Modal.js
  src/components/RecMiniSlide.js
  src/components/ShowData.js
  src/components/Snow.js
  src/components/Streaming.js
  src/components/Top5.js
  src/index.js
  src/layout/Header.js
  src/page/About.js
  src/page/Home.js
  src/page/Search.js
  src/page/ShortFilm.css
  src/page/ShortFilm.js
Labels: 💻Front, 〄CI/CD

#325 [Feat - front]: react player ui 변경
  src/App.js
  src/components/MyWish.js
  src/layout/Header.js
  src/page/Login.js
  src/page/ShortFilm.js
  src/page/ShortFilm2.js
Labels: 👨🏻‍💻개발, 💻Front, 💡수정, Priority: Urgent

#328 [Feat]: 숏필름 vodname에 링크 추가
  src/components/ShowData.js
  src/page/ShortFilm2.js
Labels: 👨🏻‍💻개발, 💻Front, Priority: Urgent

#329 [Deploy]: 숏필름 vodname에 링크 추가
  src/components/ShowData.js
  src/page/ShortFilm2.js
Labels: 💻Front, 〄CI/CD
